# Generated by Django 4.1.7 on 2023-03-05 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='meta_info',
            field=models.TextField(blank=True, null=True, verbose_name='Some metadata about the menu'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='url',
            field=models.CharField(help_text="Use reverse URL. Example: 'main:menu_example'", max_length=100),
        ),
    ]
